# Generated by Django 6.0.7 on 2026-07-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('H', 'Half Day'), ('LV', 'Leave')], default='A', max_length=2),
        ),
    ]
