# Generated by Django 6.0.7 on 2026-07-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
