# Generated by Django 6.0.7 on 2026-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_employee_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
